- name: firewall release http
  service: http
  permanent: yes
  state: enabled

- name: firewall release https
  service: https
  permanent: yes
  state: enabled

- name: firewall release mariadb
  firewalld:
    service: mysql
    permanent: yes
    state: enabled

- name: firewalld reload
  command: firewall-cmd --reload
