- name: Add mariaDB repository
  yum_repository:
    name: MariaDB
    description: MariaDB repo
    baseurl: http://yum.mariadb.org/10.4/centos7-amd64
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: true

- name: Install mariadb
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - MariaDB-server
      - MariaDB-client

- name: start and enable mariadb
  service:
    name: mariadb
    state: started
    enabled: yes
